import PricingUi from '@/Components/PricingUi'
import Head from 'next/head'
import { Main } from 'next/document';




export default function Home() {
  return (
    <>
      <Head>
        <title>Pricing UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <PricingUi />
      </main>
    </>
  )
}


